run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tests
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Staticcheck is go vet on steroids
    - typecheck     # Type check
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspellings
    - gocritic      # Highly extensible linter
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security problems
    - bodyclose     # Check HTTP response body close
    - errorlint     # Error wrapping
    - exportloopref # Check loop variable capture
    - gocyclo       # Cyclomatic complexity
    - unconvert     # Remove unnecessary type conversions

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gocyclo:
    min-complexity: 15
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true
  
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
    
issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    
    # Exclude known false positives
    - text: "G404:"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
